GET localhost:8080/api/v1/availableTimes/2022-03-06
###
POST localhost:8080/api/v1/booking
Content-Type: application/json

{
  "date": "2022-03-06 22:00",
  "numGuests": 3,
  "occasion": "1",
  "name": "mofo",
  "email": "mogo",
  "telephone": "dasdsa"
}